"""Props: everything the player walks up to, and the dressing around it.

Grids are art pixels at PLAY (2 texture px each, bible/art.json), so one
character here is the same size on screen as one pixel of a character sheet.
They used to be saved at 3, which is what the art-director's first review
found: a crate's pixel half again the size of the pixel of the woman
standing on it (art/reviews/2026-09-16/).

`o` is still the outline colour, but only inside a shape -- a hole, a seam,
a screen's frame. Every `o` that touches air is rewritten by `edge()` into a
step of the colour it sits against, which is the shading bar's rule: an edge
is the darker step of the local colour, and the lit edge (the step above the
face) sits on the light side only. That used to be done by hand and so was
not done at all: 19 props carried a flat black ring round the whole
silhouette.
"""
import os
import re
from pixel import draw, save, preview, sheet, PALETTE
from make_tiles import solid, px, hline, vline, rect

HERE = os.path.dirname(os.path.abspath(__file__))
PLAY = 2   # texture px per art px on the play plane

L = {
    "o": "outline", "s": "steel1", "S": "steel2", "t": "steel3", "T": "steel4",
    "c": "cyan", "C": "cyan_d", "m": "magenta", "M": "magenta_d", "a": "amber", "A": "amber_d",
    "g": "green", "G": "green_d", "v": "violet", "V": "violet_d", "r": "red", "R": "red_d",
    "w": "white", "y": "grey", "Y": "grey_d", "k": "black", "K": "black_l", "b": "bg0",
    "B": "bg1", "d": "bg2", "D": "bg3", "u": "rust1", "U": "rust2", "n": "sodium", "W": "warm",
    "e": "concrete1", "E": "concrete2", "l": "olive", "L": "olive_l",
    # the steps the ramps needed and did not have a character for. Without a
    # darker steel than steel1 there was nothing to edge a steel prop with
    # except black, which is how every prop ended up with the same ring.
    "z": "steel0", "q": "concrete0", "Q": "concrete3",
    "x": "rust0", "X": "rust3", "j": "olive_d", "J": "olive_ll",
    "h": "amber_l", "H": "red_l", "i": "cyan_l", "N": "magenta_l",
}

# --- The ramps, for the edge pass ----------------------------------------------------
# Each is one material dark -> light. A step's neighbours are what an edge is
# drawn with, so this is the shading bar written as data.

RAMPS = [
    ["void", "bg0", "bg1", "bg2", "bg3"],
    ["steel0", "steel1", "steel2", "steel3", "steel4"],
    ["concrete0", "concrete1", "concrete2", "concrete3"],
    ["rust0", "rust1", "rust2", "rust3"],
    ["olive_d", "olive", "olive_l", "olive_ll"],
    ["amber_d", "amber", "amber_l"],
    ["cyan_d", "cyan", "cyan_l"],
    ["magenta_d", "magenta", "magenta_l"],
    ["red_d", "red", "red_l"],
    ["violet_d", "violet"],
    ["green_d", "green"],
    ["grey_d", "grey", "white"],
    ["chrome_d", "chrome"],
    ["black", "black_l"],
    ["sodium", "warm"],
]
_STEP_OF = {name: (i, j) for i, ramp in enumerate(RAMPS) for j, name in enumerate(ramp)}


def _neighbour_step(name, lighter):
    """The step above or below `name` in its ramp; `name` itself at the end."""
    at = _STEP_OF.get(name)
    if at is None:
        return name
    i, j = at
    ramp = RAMPS[i]
    j2 = min(j + 1, len(ramp) - 1) if lighter else max(j - 1, 0)
    return ramp[j2]


_CHAR_OF = {}
for _k, _v in L.items():
    _CHAR_OF.setdefault(_v, _k)

AIR = {".", " "}


def edge(rows, light="ul"):
    """Draw the silhouette's edge from the shape, instead of typing it.

    Every cell that touches air becomes a step of its own colour: the step
    above it where the light hits (the top and the left, unless the room says
    otherwise), the step below it everywhere else. That is the shading bar's
    rule, and having it here rather than in the grids is why it is now
    actually obeyed -- typed by hand it was skipped, and nineteen props
    carried a flat black ring round the whole silhouette instead.

    A grid therefore carries shape and material only. `o` still means the
    outline colour and is left alone: inside a shape it is a hole, a seam or
    a screen's frame, all of which are meant to be dark.
    """
    h = len(rows)
    w = max(len(r) for r in rows)
    g = [list(r.ljust(w, ".")[:w]) for r in rows]
    up, left = "u" in light, "l" in light

    def at(x, y):
        return g[y][x] if 0 <= x < w and 0 <= y < h else "."

    out = [row[:] for row in g]
    for y in range(h):
        for x in range(w):
            c = g[y][x]
            if c in AIR or c == "o" or c not in L:
                continue
            around = ((0, -1), (0, 1), (-1, 0), (1, 0))
            if not any(at(x + dx, y + dy) in AIR for dx, dy in around):
                continue                       # interior
            lit = ((at(x, y - 1) in AIR) if up else (at(x, y + 1) in AIR)) or \
                  ((at(x - 1, y) in AIR) if left else (at(x + 1, y) in AIR))
            want = _neighbour_step(L[c], lighter=lit)
            out[y][x] = _CHAR_OF.get(want, c)
    return ["".join(row) for row in out]


def emit(name, rows, sub="props", light="ul"):
    img = draw(edge(rows, light), L)
    save(img, "%s/%s.png" % (sub, name), scale=PLAY)
    return img


SAVE_TERMINAL = [   # 36x66 art px at PLAY
    "......ssssssssssssssssssssssss......",
    "......ssssssssssssssssssssssss......",
    ".....sssssssssssssssssssssssssss....",
    ".....sssSSSSSSSSSSSSSSSSSSSSSsss....",
    ".....sssSSSSSSSSSSSSSSSSSSSSSsss....",
    ".....sssSooooooooooooooooooSSsss....",
    ".....sssSoocccccccccccccccoSSsss....",
    ".....sssSoocccccccccccccccoSSsss....",
    ".....sssSoocCCCCCCCCCCCCccoSSsss....",
    ".....sssSoocCCwwwwwwCCCCccoSSsss....",
    ".....sssSoocCCwwwwwwCCCCccoSSsss....",
    ".....sssSoocCCCCCCCCCCCCccoSSsss....",
    ".....sssSoocCCCCCCCCCCCCccoSSsss....",
    ".....sssSoocCCCCCCCCCCCCccoSSsss....",
    ".....sssSoocCCCCCCCCCCCCccoSSsss....",
    ".....sssSoocccccccccccccccoSSsss....",
    ".....sssSoocccccccccccccccoSSsss....",
    ".....sssSooooooooooooooooooSSsss....",
    ".....sssSSSSSSSSSSSSSSSSSSSSSsss....",
    ".....sssSSSSSSSSSSSSSSSSSSSSSsss....",
    ".....sssssssssssssssssssssssssss....",
    ".....ssssoooooooooooooooooosssss....",
    ".....ssssoooooooooooooooooosssss....",
    ".....ssssooaaaoaaaooaaaoaaosssss....",
    ".....ssssoooooooooooooooooosssss....",
    ".....ssssoooooooooooooooooosssss....",
    ".....ssssooaaaoaaaooaaaoaaosssss....",
    ".....ssssoooooooooooooooooosssss....",
    ".....ssssoooooooooooooooooosssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....ssssssssssmmmssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    ".....sssssssssssssssssssssssssss....",
    "...ssssssssssssssssssssssssssssss...",
    "...ssssssssssssssssssssssssssssss...",
    "...ssssssssssssssssssssssssssssss...",
]

CHEST = [   # 36x27 art px at PLAY
    "....................................",
    "....................................",
    "......llllllllllllllllllllllll......",
    ".....llllllllllllllllllllllllllll...",
    ".....llllllllllllllllllllllllllll...",
    "...lllLLLLLLLLLLLLLLLLLLLLLLLLlllll.",
    "...llllllllllllllaaalllllllllllll...",
    "...llllllllllllllaaalllllllllllll...",
    "...llllllllllllllaaalllllllllllll...",
    "...llllllllllllllllllllllllllllll...",
    "...llllllllllllllaaalllllllllllll...",
    "...llllllllllllllaaalllllllllllll...",
    "...llllllllllllllooolllllllllllll...",
    "...llllllllllllllooolllllllllllll...",
    "...llllllllllllllllllllllllllllllll.",
    "...llllllllllllllllllllllllllllll...",
    "...llllllllllllllllllllllllllllll...",
    "...llllllllllllllllllllllllllllll...",
    "...llllllllllllllllllllllllllllll...",
    "...llllllllllllllllllllllllllllll...",
    "...llllllllllllllllllllllllllllll...",
    "...llllllllllllllllllllllllllllll...",
    "...llllllllllllllllllllllllllllll...",
    "...llllllllllllllllllllllllllllll...",
    ".....lllllllllllllllllllllllll......",
    ".....lllllllllllllllllllllllll......",
    "....................................",
]

PROGRAM_TERMINAL = [   # 30x54 art px at PLAY
    "......SSSSSSSSSSSSSSSSSS......",
    "......SSSSSSSSSSSSSSSSSS......",
    ".....SSSSSSSSSSSSSSSSSSSSS....",
    ".....SSSoooooooooooooooSSS....",
    ".....SSSoooooooooooooooSSS....",
    ".....SSSoggggggggggggooSSS....",
    ".....SSSoGGwwwGGGGGGGooSSS....",
    ".....SSSoGGwwwGGGGGGGooSSS....",
    ".....SSSoGGGGGGwwwwwGooSSS....",
    ".....SSSoGGGGGGGGGGGGooSSS....",
    ".....SSSoGGGGGGGGGGGGooSSS....",
    ".....SSSoggggggggggggooSSS....",
    ".....SSSoooooooooooooooSSS....",
    ".....SSSoooooooooooooooSSS....",
    ".....SSSSSSSSSSSSSSSSSSSSS....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssoaaossossossoaasss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssoaaoaaossossoaasss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssoaaossoaaossoaasss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    ".....sssssssssssssssssssss....",
    "...ssssssssssssssssssssssss...",
    "...ssssssssssssssssssssssss...",
    "..............................",
]

GADGET_CRATE = [   # 36x27 art px at PLAY
    "....................................",
    "....................................",
    "...ssssssssssssssssssssssssssssss...",
    "..sssssssssssssssssssssssssssssssss.",
    "..sssssssssssssssssssssssssssssssss.",
    "..sssSSSSSSSSSSSSSSSSSSSSSSSSSSSsss.",
    "..sssSccccccccccccccccccccccccSSsss.",
    "..sssSccccccccccccccccccccccccSSsss.",
    "..sssSSSSSSSSSSSSSSSSSSSSSSSSSSSsss.",
    "..sssssssssssssssssssssssssssssssss.",
    "..sssssssssssssssssssssssssssssssss.",
    "..sssssssssssssssssssssssssssssssss.",
    "..sssssssssssssssssssssssssssssssss.",
    "..sssssssssssssssssssssssssssssssss.",
    "..sssSSSSSSSSSSSSSSSSSSSSSSSSSSSsss.",
    "..sssSSSSSSSSScccccccSSSSSSSSSSSsss.",
    "..sssSSSSSSSSScccccccSSSSSSSSSSSsss.",
    "..sssSSSSSSSSScTTTTTcSSSSSSSSSSSsss.",
    "..sssSSSSSSSSScccccccSSSSSSSSSSSsss.",
    "..sssSSSSSSSSScccccccSSSSSSSSSSSsss.",
    "..sssSSSSSSSSSSSSSSSSSSSSSSSSSSSsss.",
    "..sssssssssssssssssssssssssssssssss.",
    "..sssssssssssssssssssssssssssssssss.",
    "...ssssssssssssssssssssssssssssss...",
    "....................................",
    "....................................",
    "....................................",
]

IMPLANT_CRATE = [   # 36x27 art px at PLAY
    "....................................",
    "....................................",
    "...wwwwwwwwwwwwwwwwwwwwwwwwwwwwww...",
    "..wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.",
    "..wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.",
    "..wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.",
    "..wwwwwwwwwwwwwwwrrrwwwwwwwwwwwwwww.",
    "..wwwwwwwwwwwwwwwrrrwwwwwwwwwwwwwww.",
    "..wwwwwwwwwwwwwwwrrrwwwwwwwwwwwwwww.",
    "..wwwwwwwwwwwwrrrrrrrrrwwwwwwwwwwww.",
    "..wwwwwwwwwwwwrrrrrrrrrwwwwwwwwwwww.",
    "..wwwwwwwwwwwwrrrrrrrrrwwwwwwwwwwww.",
    "..wwwwwwwwwwwwwwwrrrwwwwwwwwwwwwwww.",
    "..wwwwwwwwwwwwwwwrrrwwwwwwwwwwwwwww.",
    "..wwwwwwwwwwwwwwwrrrwwwwwwwwwwwwwww.",
    "..wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.",
    "..wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.",
    "..wwwyyyyyyyyyyyyyyyyyyyyyyyyyyywww.",
    "..wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.",
    "..wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.",
    "..wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.",
    "..yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy.",
    "..yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy.",
    "...yyyyyyyyyyyyyyyyyyyyyyyyyyyyyy...",
    "....................................",
    "....................................",
    "....................................",
]

HP_UP = [   # 18x21 art px at PLAY, redrawn: the 3:2 draft lost the shape
    "..................",
    "..................",
    "....rrrrrrrrrr....",
    "...rrrrrrrrrrrr...",
    "...rrrrrwwrrrrr...",
    "...rrrrrwwrrrrr...",
    "...rrrrrwwrrrrr...",
    "...rrwwwwwwwwrr...",
    "...rrwwwwwwwwrr...",
    "...rrrrrwwrrrrr...",
    "...rrrrrwwrrrrr...",
    "...rrrrrwwrrrrr...",
    "...rrrrrrrrrrrr...",
    "....rrrrrrrrrr....",
    "..................",
    "..................",
    "..................",
    "..................",
    "..................",
    "..................",
    "..................",
]

RAM_UP = [   # 18x21 art px at PLAY, redrawn: the 3:2 draft lost the shape
    "..................",
    "..vvvvvvvvvvvvvv..",
    "..vvvvvvvvvvvvvv..",
    "..vvVVVVVVVVVVvv..",
    "..vvVVVVVVVVVVvv..",
    "..vvVVwwwwwwVVvv..",
    "..vvVVwwwwwwVVvv..",
    "..vvVVwwVVVVwwvv..",
    "..vvVVwwwwwwVVvv..",
    "..vvVVwwwwwwVVvv..",
    "..vvVVVVVVVVVVvv..",
    "..vvvvvvvvvvvvvv..",
    "..vvvvvvvvvvvvvv..",
    "..S..S..SS..S..S..",
    "..S..S..SS..S..S..",
    "..................",
    "..................",
    "..................",
    "..................",
    "..................",
    "..................",
]

CHIP = [   # 18x21 art px at PLAY, redrawn: the 3:2 draft lost the shape
    "..................",
    "..................",
    "..................",
    ".....cccccccc.....",
    ".....cccccccc.....",
    ".....ccwwwwcc.....",
    ".....ccwwwwcc.....",
    ".....ccwwwwcc.....",
    ".....ccwwwwcc.....",
    ".....cccccccc.....",
    ".....cccccccc.....",
    ".....S..SS..S.....",
    ".....S..SS..S.....",
    "..................",
    "..................",
    "..................",
    "..................",
    "..................",
    "..................",
    "..................",
    "..................",
]

DOOR_FRAME = [   # 30x90 art px at PLAY
    "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
    "TTTccccccccccccccccccccccccTTT",
    "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "tttbbbbbbbbbbbbbbbbbbbbbbbbttt",
    "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
]

BREACH_DOOR = [   # 30x87 art px at PLAY
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "sssSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "sssSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "sssSSoooooooooooooooooooooSSSS",
    "sssSSorrrrrrrrrrrrrrrrrrooSSSS",
    "sssSSorrrrrrrrrrrrrrrrrrooSSSS",
    "sssSSorrRRRRRRRRRRRRRRRrooSSSS",
    "sssSSorrRRRRRRRRRRRRRRRrooSSSS",
    "sssSSorrRRRRRRRRRRRRRRRrooSSSS",
    "sssSSorrrrrrrrrrrrrrrrrrooSSSS",
    "sssSSoooooooooooooooooooooSSSS",
    "sssSSoooooooooooooooooooooSSSS",
    "sssSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "sssSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "sssSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "sssSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "sssSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "sssSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "sssSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "sssSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "sssSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
]

GRATE = [   # 30x30 art px at PLAY
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSooooooSSooooooSooooooSSSSSS",
    "SSSooooooSSooooooSooooooSSSSSS",
    "SSSooooooSSooooooSooooooSSSSSS",
    "SSSooooooSSooooooSooooooSSSSSS",
    "SSSooooooSSooooooSooooooSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSooooooSSooooooSooooooSSSSSS",
    "SSSooooooSSooooooSooooooSSSSSS",
    "SSSooooooSSooooooSooooooSSSSSS",
    "SSSooooooSSooooooSooooooSSSSSS",
    "SSSooooooSSooooooSooooooSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSooooooSSooooooSooooooSSSSSS",
    "SSSooooooSSooooooSooooooSSSSSS",
    "SSSooooooSSooooooSooooooSSSSSS",
    "SSSooooooSSooooooSooooooSSSSSS",
    "SSSooooooSSooooooSooooooSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSooooooSSooooooSooooooSSSSSS",
    "SSSooooooSSooooooSooooooSSSSSS",
    "SSSooooooSSooooooSooooooSSSSSS",
    "SSSooooooSSooooooSooooooSSSSSS",
    "SSSooooooSSooooooSooooooSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
]

LIFT_DECK = [   # 30x12 art px at PLAY
    "aaaaaakkkkkkaaaaaakkkkkkaaaaaa",
    "aaaaaakkkkkkaaaaaakkkkkkaaaaaa",
    "aaaaaakkkkkkaaaaaakkkkkkaaaaaa",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "ssssssssssssssssssssssssssssss",
    "ssSsssSSsssSsssSSsssSsssSSsssS",
    "ssSsssSSsssSsssSSsssSsssSSsssS",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssss",
    "..............................",
]

TEASE_CRATE = [   # 24x24 art px at PLAY
    "...aaaaaaaaaaaaaaaaaa...",
    "...aaaaaaaaaaaaaaaaaa...",
    "..aaaaaaaaaaaaaaaaaaaaa.",
    "..aaaAAAAAAAAAAAAAAAaaa.",
    "..aaaAAAAAAAAAAAAAAAaaa.",
    "..aaaAaaaaaaaaaaaaAAaaa.",
    "..aaaAaaAAAAAAAAAaAAaaa.",
    "..aaaAaaAAAAAAAAAaAAaaa.",
    "..aaaAaaAaaaaaaAAaAAaaa.",
    "..aaaAaaAaacccaAAaAAaaa.",
    "..aaaAaaAaacccaAAaAAaaa.",
    "..aaaAaaAaacccaAAaAAaaa.",
    "..aaaAaaAaaaaaaAAaAAaaa.",
    "..aaaAaaAaaaaaaAAaAAaaa.",
    "..aaaAaaAAAAAAAAAaAAaaa.",
    "..aaaAaaaaaaaaaaaaAAaaa.",
    "..aaaAaaaaaaaaaaaaAAaaa.",
    "..aaaAAAAAAAAAAAAAAAaaa.",
    "..aaaaaaaaaaaaaaaaaaaaa.",
    "..aaaaaaaaaaaaaaaaaaaaa.",
    "..aaaaaaaaaaaaaaaaaaaaa.",
    "...aaaaaaaaaaaaaaaaaa...",
    "...aaaaaaaaaaaaaaaaaa...",
    "........................",
]

SIGN_PANEL = [   # 18x18 art px at PLAY
    "tttttttttttttttttt",
    "tttttttttttttttttt",
    "tttttttttttttttttt",
    "tttBBBBBBBBBBBBttt",
    "tttBBBBBBBBBBBBttt",
    "tttBBBBBBBBBBBBttt",
    "tttBBBBBBBBBBBBttt",
    "tttBBBBBBBBBBBBttt",
    "tttBBBBBBBBBBBBttt",
    "tttBBBBBBBBBBBBttt",
    "tttBBBBBBBBBBBBttt",
    "tttBBBBBBBBBBBBttt",
    "tttBBBBBBBBBBBBttt",
    "tttBBBBBBBBBBBBttt",
    "tttBBBBBBBBBBBBttt",
    "tttttttttttttttttt",
    "tttttttttttttttttt",
    "tttttttttttttttttt",
]
SIGN_PANEL_WARN = [r.replace("t", "R") for r in SIGN_PANEL]

BREACH_TERMINAL = [   # 18x24 art px at PLAY
    "...SSSSSSSSSSSS...",
    "...SSSSSSSSSSSS...",
    "..SSSSSSSSSSSSSSS.",
    "..SSSoooooooooSSS.",
    "..SSSoooooooooSSS.",
    "..SSSorrrrrrooSSS.",
    "..SSSorrRRRrooSSS.",
    "..SSSorrRRRrooSSS.",
    "..SSSorrrrrrooSSS.",
    "..SSSoooooooooSSS.",
    "..SSSoooooooooSSS.",
    "..SSSSSSSSSSSSSSS.",
    "..SSSaSSaSSaSSSSS.",
    "..SSSaSSaSSaSSSSS.",
    "..SSSSSSSSSSSSSSS.",
    "...SSSSSSSSSSSS...",
    "...SSSSSSSSSSSS...",
    "......SSSSSS......",
    "......SSSSSS......",
    "......SSSSSS......",
    "......SSSSSS......",
    ".....SSSSSSSSS....",
    ".....SSSSSSSSS....",
    "..................",
]

PIPE_H = [   # 60x9 art px at PLAY
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "tttSSSSSSSSSSSSSStSSSSSSSSSSSSSSSttSSSSSSSSSSSSSSSSSStSSSSSS",
    "tttSSSSSSSSSSSSSStSSSSSSSSSSSSSSSttSSSSSSSSSSSSSSSSSStSSSSSS",
    "ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
    "ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
    "............................................................",
]

PIPE_V = [   # 9x60 art px at PLAY
    "SSSSSSSSS",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSStsss",
    "SSSSSSSSS",
]

VENT = [   # 30x18 art px at PLAY
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSbbbbbbbbbbbbbbbbbbbbbbbbSSS",
    "SSSbbbbbbbbbbbbbbbbbbbbbbbbSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSbbbbbbbbbbbbbbbbbbbbbbbbSSS",
    "SSSbbbbbbbbbbbbbbbbbbbbbbbbSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSbbbbbbbbbbbbbbbbbbbbbbbbSSS",
    "SSSbbbbbbbbbbbbbbbbbbbbbbbbSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSbbbbbbbbbbbbbbbbbbbbbbbbSSS",
    "SSSbbbbbbbbbbbbbbbbbbbbbbbbSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "..............................",
]

POSTER_A = [   # 24x30 art px at PLAY
    "MMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMmmmmmmmmmmmmmmmmmmMMM",
    "MMMmmmmmmmmmmmmmmmmmmMMM",
    "MMMmmMMMmmmmmmMMMmmmmMMM",
    "MMMmmmmmmmmmmmmmmmmmmMMM",
    "MMMmmmmmmmmmmmmmmmmmmMMM",
    "MMMmmmwwwwwwwwwwwwmmmMMM",
    "MMMmmmwwwwwwwwwwwwmmmMMM",
    "MMMmmmwwwwwwwwwwwwmmmMMM",
    "MMMmmmmmmmmmmmmmmmmmmMMM",
    "MMMmmmmmmmmmmmmmmmmmmMMM",
    "MMMmmmmmmmmmmmmmmmmmmMMM",
    "MMMmmMMMMMMMMMMMMMMMmMMM",
    "MMMmmmmmmmmmmmmmmmmmmMMM",
    "MMMmmmmmmmmmmmmmmmmmmMMM",
    "MMMmmmmmmmmmmmmmmmmmmMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMwwwwwwwwwMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMM",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
]
POSTER_B = [r.replace("M", "C").replace("m", "c") for r in POSTER_A]

LAMP = [   # 12x15 art px at PLAY
    ".....SSS....",
    ".....SSS....",
    "...SSSSSS...",
    "..SSSSSSSSS.",
    "..SSSSSSSSS.",
    "..nnnnnnnnn.",
    "..WWWWWWWWW.",
    "..WWWWWWWWW.",
    "...WWWWWW...",
    ".....WWW....",
    ".....WWW....",
    "............",
    "............",
    "............",
    "............",
]

WINDOW = [   # 36x24 art px at PLAY
    "tttttttttttttttttttttttttttttttttttt",
    "tttttttttttttttttttttttttttttttttttt",
    "tttttttttttttttttttttttttttttttttttt",
    "tttWWWWWWWWWWWWWWtttWWWWWWWWWWWWWttt",
    "tttWWWWWWWWWWWWWWtttWWWWWWWWWWWWWttt",
    "tttWWWWWWWWWWWWWWtttWWWWWWWWWWWWWttt",
    "tttWWWWWnWWWWWWWWtttWWWWWWWWWWWWWttt",
    "tttWWWWWnWWWWWWWWtttWWWWWWWWWWWWWttt",
    "tttWWWWWWWWWWWWWWtttWWWWWWWWWnWWWttt",
    "tttWWWWWWWWWWWWWWtttWWWWWWWWWWWWWttt",
    "tttWWWWWWWWWWWWWWtttWWWWWWWWWWWWWttt",
    "tttttttttttttttttttttttttttttttttttt",
    "tttWWWWWWWWWWWWWWtttWWWWWWWWWWWWWttt",
    "tttWWWWWWWWWWWWWWtttWWWWWWWWWWWWWttt",
    "tttWWWWWWWWWWWWWWtttWWWWWWWWWWWWWttt",
    "tttWWWWWWWWWnnWWWtttWWWWWWWWWWWWWttt",
    "tttWWWWWWWWWnnWWWtttWWWWWWWWWWWWWttt",
    "tttWWWWWWWWWWWWWWtttWWWWWWWWWWWWWttt",
    "tttWWWWWWWWWWWWWWtttWWWWWWWWWWWWWttt",
    "tttWWWWWWWWWWWWWWtttWWWWWWWWWWWWWttt",
    "tttttttttttttttttttttttttttttttttttt",
    "tttttttttttttttttttttttttttttttttttt",
    "tttttttttttttttttttttttttttttttttttt",
    "....................................",
]

CRATES = [   # 36x30 art px at PLAY
    "....................................",
    "....................................",
    "......uuuuuuuuuuuuuuuuuu............",
    "......uuuuuuuuuuuuuuuuuu............",
    "......uuuuuuuuuuuuuuuuuu............",
    "......uuuUUUUUUUUUUUUuuu............",
    "......uuuuuuuuuuuuuuuuuu............",
    "......uuuuuuuuuuuuuuuuuu............",
    "......uuuuuuuuuuuuuuuuuu............",
    "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
    "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
    "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
    "uuuUUUUUUUUUUUUuuuuuuUUUUUUUUUUUUuuu",
    "uuuUUUUUUUUUUUUuuuuuuUUUUUUUUUUUUuuu",
    "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
    "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
    "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
    "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
    "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
    "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
    "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
    "....................................",
    "....................................",
    "....................................",
    "....................................",
    "....................................",
    "....................................",
    "....................................",
    "....................................",
    "....................................",
]

BARREL = [   # 18x24 art px at PLAY
    "...SSSSSSSSSSSS...",
    "...SSSSSSSSSSSS...",
    "..SSSSSSSSSSSSSSS.",
    "..SSSeeeeeeeeeSSS.",
    "..SSSeeeeeeeeeSSS.",
    "..SSSeeeeeeeeeSSS.",
    "..SSSSSSSSSSSSSSS.",
    "..SSSSSSSSSSSSSSS.",
    "..SSSeeeeeeeeeSSS.",
    "..SSSeeeeeeeeeSSS.",
    "..SSSeeeeeeeeeSSS.",
    "..SSSeeeeeeeeeSSS.",
    "..SSSeeeeeeeeeSSS.",
    "..SSSeeeeeeeeeSSS.",
    "..SSSSSSSSSSSSSSS.",
    "..SSSeeeeeeeeeSSS.",
    "..SSSeeeeeeeeeSSS.",
    "..SSSeeeeeeeeeSSS.",
    "..SSSeeeeeeeeeSSS.",
    "..SSSeeeeeeeeeSSS.",
    "..SSSeeeeeeeeeSSS.",
    "..SSSSSSSSSSSSSSS.",
    "..SSSSSSSSSSSSSSS.",
    "...SSSSSSSSSSSS...",
]

MONITOR = [   # 24x18 art px at PLAY
    "SSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSggggggggggggggggggSSS",
    "SSSggggggggggggggggggSSS",
    "SSSggGGGGGGGGGGGGGGGgSSS",
    "SSSggGwwwGGGGGGGGGGGgSSS",
    "SSSggGwwwGGGGGGGGGGGgSSS",
    "SSSggGGGGGGGwwwwwGGGgSSS",
    "SSSggGGGGGGGGGGGGGGGgSSS",
    "SSSggGGGGGGGGGGGGGGGgSSS",
    "SSSggggggggggggggggggSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSS",
    ".........SSSSSS.........",
    ".........SSSSSS.........",
    "......SSSSSSSSSSSS......",
]

CABLE = [   # 60x9 art px at PLAY
    "............................................................",
    "............................................................",
    "ooo......................................................ooo",
    "...ooo................................................ooo...",
    "...ooo................................................ooo...",
    "......oooooo....................................oooooo......",
    "............oooooooooooooooooooooooooooooooooooo............",
    "............oooooooooooooooooooooooooooooooooooo............",
    "............................................................",
]

FAN = [   # 30x30 art px at PLAY
    "...SSSSSSSSSSSSSSSSSSSSSSSS...",
    "...SSSSSSSSSSSSSSSSSSSSSSSS...",
    "..SSSSSSSSSSSSSSSSSSSSSSSSSSS.",
    "SSSbbbbbbbbbbbbbbbbbbbbbbbbSSS",
    "SSSbbbbbbbbbbbbbbbbbbbbbbbbSSS",
    "SSSbbbbbbbbbbbSSSbbbbbbbbbbSSS",
    "SSSbbbbbbbbbSSSSSSbbbbbbbbbSSS",
    "SSSbbbbbbbbbSSSSSSbbbbbbbbbSSS",
    "SSSbbbbbSSSSSSSSSSSSSSSbbbbSSS",
    "SSSbbbbbbbbSSSSSSSSSbbbbbbbSSS",
    "SSSbbbbbbbbSSSSSSSSSbbbbbbbSSS",
    "SSSbbbbbbbbbSSSSSSbbbbbbbbbSSS",
    "SSSbbbbbbbbbbbSSSbbbbbbbbbbSSS",
    "SSSbbbbbbbbbbbSSSbbbbbbbbbbSSS",
    "SSSbbbbbbbbbSSSSSSbbbbbbbbbSSS",
    "SSSbbbbbbbbSSSSSSSSSbbbbbbbSSS",
    "SSSbbbbbbbbSSSSSSSSSbbbbbbbSSS",
    "SSSbbbbbSSSSSSSSSSSSSSSbbbbSSS",
    "SSSbbbbbbbbbSSSSSSbbbbbbbbbSSS",
    "SSSbbbbbbbbbSSSSSSbbbbbbbbbSSS",
    "SSSbbbbbbbbbbbSSSbbbbbbbbbbSSS",
    "SSSbbbbbbbbbbbbbbbbbbbbbbbbSSS",
    "SSSbbbbbbbbbbbbbbbbbbbbbbbbSSS",
    "SSSbbbbbbbbbbbbbbbbbbbbbbbbSSS",
    "SSSbbbbbbbbbbbbbbbbbbbbbbbbSSS",
    "SSSbbbbbbbbbbbbbbbbbbbbbbbbSSS",
    "..SSSSSSSSSSSSSSSSSSSSSSSSSSS.",
    "...SSSSSSSSSSSSSSSSSSSSSSSS...",
    "...SSSSSSSSSSSSSSSSSSSSSSSS...",
    "..............................",
]

AWNING = [   # 90x12 art px at PLAY
    "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
    "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
    "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
    "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
    "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
    "mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.mm.",
]

NEON_TUBE_H = [   # 60x4 art px at PLAY; 120x8 texture, three px off the
    # old 123 because 41x3 at 3 does not divide by 2 and a round number does
    "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
    "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
    "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
    "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
]
NEON_TUBE_M = [r.replace("c", "m") for r in NEON_TUBE_H]

BODY = [   # 48x18 art px at PLAY
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    ".........llllllll...............................",
    ".........llllllll...............................",
    "........lllllllllluuuuuuuuuuuuuuuuuuuukkkk......",
    "......lllLLLLLllluuuuuuuuuuuuuuuuuuuuukkkkkk....",
    "......lllLLLLLllluuuuuuuuuuuuuuuuuuuuukkkkkk....",
    "......llllllllllluuuUUUuuuuuuuuuuuuuuukkkkkk....",
    "........llllllllluuuuuuuuuuuuuuuuuuuuuuuuu......",
    "........llllllllluuuuuuuuuuuuuuuuuuuuuuuuu......",
    ".........llllllll.uuuuuuuuuuuuuuuuuuuuu.........",
]

if __name__ == "__main__":
    items = {
        "save_terminal": SAVE_TERMINAL, "chest": CHEST, "program_terminal": PROGRAM_TERMINAL,
        "gadget_crate": GADGET_CRATE, "implant_crate": IMPLANT_CRATE, "hp_up": HP_UP, "ram_up": RAM_UP,
        "chip": CHIP, "door_frame": DOOR_FRAME, "breach_door": BREACH_DOOR, "grate": GRATE,
        "lift_deck": LIFT_DECK, "tease_crate": TEASE_CRATE, "sign_panel": SIGN_PANEL,
        "sign_panel_warn": SIGN_PANEL_WARN, "breach_terminal": BREACH_TERMINAL,
        "pipe_h": PIPE_H, "pipe_v": PIPE_V, "vent": VENT, "poster_a": POSTER_A, "poster_b": POSTER_B,
        "lamp": LAMP, "window": WINDOW, "crates": CRATES, "barrel": BARREL, "monitor": MONITOR,
        "cable": CABLE, "fan": FAN, "awning": AWNING, "neon_tube_c": NEON_TUBE_H, "neon_tube_m": NEON_TUBE_M,
        "body": BODY,
    }
    imgs = []
    for name, rows in items.items():
        w = max(len(r) for r in rows)
        rows = [r.ljust(w, ".")[:w] for r in rows]
        imgs.append(emit(name, rows))
    # one preview sheet, padded to a common height
    from PIL import Image
    H = max(i.height for i in imgs)
    W = sum(i.width + 4 for i in imgs)
    out = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    x = 0
    for i in imgs:
        out.paste(i, (x, H - i.height))
        x += i.width + 4
    preview(out, os.path.join(HERE, "preview_props.png"), 4)
    print("props written:", len(items))
