class_name UiPalette
extends RefCounted
## The interface's colours, generated by the ui-artist from ui/ui.json.
##
## Do not edit: change the palette in game/tools/art/pixel.py or the role
## in ui/ui.json and re-run `export.py --project .`.
##
## A role is what a colour means on screen, not what it looks like: the HP
## bar is HP, and if the game's red moves it moves here once. Each comment
## below says whether the role takes a palette entry -- the same colours the
## sprites are snapped onto -- or holds its own, and why.

## focus, the speaker's name, the active tab, the current room. The code had five names for it: COL_ACCENT, COL_ACTIVE, COL_NAME, COL_CURRENT, COL_SPEAKER.
## the interface's own: 153, 242, 255
const ACCENT := Color(0.6, 0.949, 1.0)

## a downgrade or a failure. Was COL_BAD, COL_WORSE, and the title's COL_WARN, which was this colour and not a warning.
## the interface's own: 255, 115, 115
const BAD := Color(1.0, 0.451, 0.451)

## a button at rest; 2.3 dE off, so it snaps.
## the palette's bg1: 20, 26, 38
const BUTTON := Color(0.0784, 0.102, 0.149)

## a button under the cursor or the focus; 1.5 dE off, so it snaps.
## the palette's bg2: 28, 36, 54
const BUTTON_HOVER := Color(0.1098, 0.1412, 0.2118)

## already the palette exactly, typed inline in the HUD.
## the palette's amber: 255, 184, 51
const CREDITS := Color(1.0, 0.7216, 0.2)

## labels, hints, anything the eye is meant to skip. Eleven files typed it and none disagreed, which is what a role looks like before it has a name.
## the interface's own: 115, 133, 163
const DIM := Color(0.451, 0.5216, 0.6392)

## the map's doors; 2.1 dE off, so it snaps.
## the palette's bg0: 13, 16, 24
const DOOR := Color(0.051, 0.0627, 0.0941)

## the focus ring and the hovered label; already the palette (dE 0.1).
## the palette's cyan: 34, 230, 255
const FOCUS := Color(0.1333, 0.902, 1.0)

## an upgrade, a quest done, a stat that went up. Was COL_GOOD and COL_BETTER.
## the interface's own: 115, 242, 153
const GOOD := Color(0.451, 0.949, 0.6)

## a hack that can be cast, against RAM's violet. A hand-lightened violet with no palette step of its own.
## the interface's own: 191, 153, 255
const HACK := Color(0.749, 0.6, 1.0)

## the health bar. Six dE off the palette's red, which is the one snap worth arguing about: the bar is the most looked-at thing on the screen.
## the interface's own: 255, 92, 92
const HP := Color(1.0, 0.3608, 0.3608)

## already the palette exactly; the code just retyped it. Also SELECTED.
## the palette's magenta: 255, 46, 148
const HP_LOW := Color(1.0, 0.1804, 0.5804)

## the panel ground, matching the theme's stylebox. The code had two: the ending screen's, which matched the theme, and the dialogue box's, 2.1 dE lighter for no reason anyone wrote down.
## the palette's outline: 11, 13, 20
const PANEL := Color(0.0431, 0.051, 0.0784)

## already the palette (dE 0.4), typed inline.
## the palette's steel2: 68, 78, 104
const PANEL_EDGE := Color(0.2667, 0.3059, 0.4078)

## the rain sheet on the title, drawn at alpha 0.35.
## the interface's own: 153, 204, 255
const RAIN := Color(0.6, 0.8, 1.0)

## already the palette (dE 0.3).
## the palette's violet: 157, 107, 255
const RAM := Color(0.6157, 0.4196, 1.0)

## the map's rooms; 1.5 dE off, under the just-noticeable difference, so it snaps.
## the palette's navy: 43, 54, 84
const ROOM := Color(0.1686, 0.2118, 0.3294)

## the map's room borders, a step lighter than the rooms themselves.
## the interface's own: 115, 140, 191
const ROOM_EDGE := Color(0.451, 0.549, 0.749)

## a save point on the map, against ACCENT's current room. A hand-lightened cyan.
## the interface's own: 89, 217, 255
const SAVE := Color(0.349, 0.851, 1.0)

## the dim over the title behind its menu, at alpha 0.35. Three dE under void and the only true black in the game.
## the interface's own: 0, 0, 13
const SCRIM := Color(0.0, 0.0, 0.051)

## the palette's magenta: 255, 46, 148
const SELECTED := Color(1.0, 0.1804, 0.5804)

## the far parallax skyline. The pair with SKYLINE_NEAR is the depth: change one and the distance changes.
## the interface's own: 140, 153, 191
const SKYLINE_FAR := Color(0.549, 0.6, 0.749)

## the near parallax skyline.
## the interface's own: 204, 217, 255
const SKYLINE_NEAR := Color(0.8, 0.851, 1.0)

## the groove a slider runs in. Two point seven dE from bg2, just over the line, and snapping it there would make a track and a hovered button the same colour, which they are not.
## the interface's own: 33, 41, 61
const SLIDER_TRACK := Color(0.1294, 0.1608, 0.2392)

## the body text. The code had two COL_TEXT, this one in the six menus and (217,230,247) in the four in-world overlays, dE 3.4 apart; no one could say which screen they were looking at, so one wins.
## the interface's own: 199, 219, 242
const TEXT := Color(0.7804, 0.8588, 0.949)

## the title's ground band; half a dE from void, so it snaps.
## the palette's void: 7, 8, 15
const TITLE_GROUND := Color(0.0275, 0.0314, 0.0588)

## the outline behind the title's 132 px letters. Colder than bg0 by 3.5 dE so the neon sits off the sky rather than on it.
## the interface's own: 5, 13, 26
const TITLE_OUTLINE := Color(0.0196, 0.051, 0.102)

## the damage flash over the whole screen. A deep red with no palette step; the palette's red_d is 22 dE away and reads brown behind a HUD.
## the interface's own: 178, 0, 31
const VIGNETTE := Color(0.698, 0.0, 0.1216)

## a caution the player can still act on, the settings panel's only orange. The title screen called its red COL_WARN as well; that one is BAD.
## the interface's own: 255, 140, 89
const WARN := Color(1.0, 0.549, 0.349)

## already the palette (dE 0.1). Also the title's COL_NEON.
## the palette's cyan: 34, 230, 255
const XP := Color(0.1333, 0.902, 1.0)
