class_name WorldGraph
extends Resource
## The district as data: every room's map cell, size and doors
## (DESIGN.md §3.4). Generated by `tools/make_stacks.gd` from the room
## specs; the map screen draws it, the tests walk it.
##
## One dictionary per room, plain values only:
##   { "id": "hall_13", "name": "Floor 13 - Hall",
##     "cell": Vector2i(2, 3), "size": Vector2i(2, 1), "save": false,
##     "doors": [ { "id": "1", "side": 1, "at": Vector2i(1, 0),
##                  "target_room": "stairwell_east", "target_door": "2" } ] }

@export var rooms: Array[Dictionary] = []


func room(room_id: StringName) -> Dictionary:
	for entry: Dictionary in rooms:
		if StringName(str(entry.get("id", ""))) == room_id:
			return entry
	return {}


func ids() -> Array[StringName]:
	var out: Array[StringName] = []
	for entry: Dictionary in rooms:
		out.append(StringName(str(entry.get("id", ""))))
	return out


## The rectangle of map cells every room fits inside.
func bounds() -> Rect2i:
	if rooms.is_empty():
		return Rect2i()
	var first: Dictionary = rooms[0]
	var rect := Rect2i(first.get("cell", Vector2i.ZERO), first.get("size", Vector2i.ONE))
	for entry: Dictionary in rooms:
		rect = rect.merge(Rect2i(entry.get("cell", Vector2i.ZERO), entry.get("size", Vector2i.ONE)))
	return rect
